name: vidclone
description: With permission from a user, downloads YouTube videos as they're released.
# version: 1.0.0
# homepage: https://www.videate.org

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1
  http: ^0.12.1
  youtube_explode_dart: # Link to 'master' to get the change from my merged PR (https://github.com/Hexer10/youtube_explode_dart/pull/69) that adds access to the channel description. Once that's released to pub, this can be switched back to just reference the new pub version (likely 1.5.2)
    git:
      url: https://github.com/Hexer10/youtube_explode_dart.git
      ref: master
  dotenv: ^2.0.0
  file: ^5.1.0
  aws_s3_client:
    git:
      url: https://github.com/mymikemiller/aws_s3_client.git
      ref: patch-2
  vidlib:
    path: ../vidlib

dev_dependencies:
  pedantic: ^1.8.0
  mockito: ^4.1.1
  test: ^1.14.2
  clippy: ^1.0.0
  crypto: ^2.1.5
