name: vidclone
description: With permission from a user, downloads YouTube videos as they're released.
# version: 1.0.0
# homepage: https://www.videate.org

environment:
  sdk: '>=2.7.0 <3.0.0'


dependencies:
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11+1
  http: ^0.12.1
  youtube_explode_dart: ^1.3.0
  dotenv: ^2.0.0
  file: ^5.1.0
  aws_s3_client: ^0.1.1
  console: ^3.1.0
  vidlib:
    path: ../vidlib

dev_dependencies:
  pedantic: ^1.8.0
  mockito: ^4.1.1
  test: ^1.14.2
  clippy: ^1.0.0
  crypto: ^2.1.5
