name: vidclone
description: With permission from a user, downloads YouTube videos as they're released.
# version: 1.0.0
# homepage: https://www.videate.org

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  googleapis: ^7.0.0
  googleapis_auth: ^1.1.0
  http: ^0.13.1
  youtube_explode_dart: ^1.10.10+2
  dotenv: ^3.0.0
  file: ^6.1.2
  quiver: ^3.0.1
  vidlib:
    path: ../vidlib

dev_dependencies:
  pedantic: ^1.8.0
  mockito: ^5.0.17
  test: ^1.14.2
  clippy: ^1.0.0
  crypto: ^3.0.0
