/** Declaration file generated by dts-gen */

export class AssetManager {
    constructor(...args: any[]);

    chunksSize(...args: any[]): void;

    commit(...args: any[]): void;

    createUploadPromises(...args: any[]): void;

    deleteAsset(...args: any[]): void;

    getAllAssets(...args: any[]): [void];

    getAsset(...args: any[]): { ok: { url: string } };

    getHealth(...args: any[]): void;

    store(...args: any[]): { ok: string };

    updateChecksum(...args: any[]): void;

    uploadChunk(...args: any[]): void;

    uploadChunkWithRetry(...args: any[]): void;

    validateFile(...args: any[]): void;

    version(...args: any[]): void;

}

