name: vidlib
description: A library for use in multiple Videate apps.
# version: 1.0.0
# homepage: https://www.videate.org

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  built_value: ^8.1.1
  duration: ^3.0.6
  xml: ^5.0.2
  file: ^6.1.0
  enum_to_string: ^2.0.1
  console: ^4.1.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.16.8
  build_runner: ^1.8.0
  built_value_generator: ^8.0.4
  built_collection: ^5.0.0
