#!/usr/bin/env bash
# This script copied from https://github.com/dfinity/internet-identity/blob/main/demos/using-dev-build/scripts/download-did-and-wasm
set -euo pipefail

# Download the Internet Identity canister's development wasm as well as its candid interface file. See dfx.json for details.
curl -sSL https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity_dev.wasm -o internet_identity.wasm
curl -sSL https://github.com/dfinity/internet-identity/releases/latest/download/internet_identity.did -o internet_identity.did
