name: vidcast
description: Hosts an rss (xml) feed of media files
# version: 1.0.0
# homepage: https://www.videate.org

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http_server: ^0.9.8+3
  xml: ^5.0.2
  mime: ^0.9.6+3
  dotenv: ^2.0.0
  vidlib:
    path: ../vidlib
dev_dependencies:
  build_runner: ^1.8.0
  pedantic: ^1.8.0
  mockito: ^4.1.1
  test: ^1.14.2
  http: ^0.12.0+4
