name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies for VidLib
      working-directory: docs
      run: pub get
    - name: Run tests
      run: pub run test

    # VidClone tests 
    - working-directory: vidclone
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test

    # VidCast tests 
    - working-directory: vidcast
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
