name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build_VidLib:
    name: Build VidLib
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies for VidLib
      working-directory: vidlib
      run: pub get
      
  Test_VidLib:
    name: Test VidLib
    needs: [Build_VidLib]
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      working-directory: vidlib
      run: pub run test
    
    # VidClone tests 
    - uses: actions/checkout@v2
    - name: Install dependencies for VidClone
      working-directory: vidclone
      run: pub get
    - name: Run tests
      working-directory: vidclone
      run: pub run test

    # VidCast tests 
#     - uses: actions/checkout@v2
#     - name: Install dependencies for VidCast
#       working-directory: vidcast
#       run: pub get
#     - name: Run tests
#       working-directory: vidcast
#       run: pub run test
