name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_VidLib:
    name: VidLib Tests
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install ffmpeg
      working-directory: vidlib
      run: apt install ffmpeg
    - name: Install pub dependencies
      working-directory: vidlib
      run: pub get
    - name: Run tests
      working-directory: vidlib
      run: pub run test
      
  test_VidClone:
    name: VidClone Tests
    runs-on: ubuntu-latest
    needs: [test_VidLib]
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pub dependencies
      working-directory: vidclone
      run: pub get
    - name: Run tests
      working-directory: vidclone
      run: pub run test

  test_VidCast:
    name: VidCast Tests
    runs-on: ubuntu-latest
    needs: [test_VidLib]
    container:
      image:  google/dart:latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pub dependencies
      working-directory: vidcast
      run: pub get
    - name: Run tests
      working-directory: vidcast
      run: pub run test
